[package]
name = "diction_ease"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
difflib = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"